### ISSUE TITLE
absolute angle positions possible?

### ISSUE THREAD

**Issue by julled** [abalakrishnan1/GIMBAL_PROJECT#1]
Hi i really love your project ! The ronin SC is very affordable.

Do you know if i can set an absolute axis angle using SBUS? Or are all controlsignals relative signals?

Thanks alot!

**Comment by abalakrishnan1** [comment]
Hey, unfortunately absolute positions are not possible since the SBUS packets set speed and have no control over encoders. Thanks for your message. We are trying to add an abs positioning feature currently.

**Comment by julled** [comment]
thx for your fast feedback, this sounds promising!
